version: "3.2"
services:
  app:
    image: shadjachaudhari/nginx:mydemo
    volumes:
      - type: bind
        source: default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000
    command: ["npm", "start"]
